jobs:
  - job: 'TestPipeline'
    timeoutInMinutes: 90
    variables:
    - template: ../variables/globals.yml

    steps:
    - template: ../steps/test-template.yml
      parameters:
        TestParameter: >-
          "Testing multiline string
          testing with single new line
          testing with double new line"